name: Terraform and Azure Function Deployment

on:
  push:
    branches:
      - main
      - feature/assignment
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Infrastructure Deployment"
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Set hard-coded Terraform output for function_app_name
        id: export-tf-output
        run: |
          # Hard-code the value for debugging
          echo "function_app_name=restaurant-api-func-debug" >> $GITHUB_OUTPUT

      # - name: Terraform Apply
      #   run: |
      #     cd terraform
      #     # Pass all variables directly on command line
      #     terraform apply -input=false -auto-approve \
      #       -var="location=westeurope" \
      #       -var="resource_group_name=restaurant-api-rg" \
      #       -var="function_app_name=restaurant-api-func-q"

      # - name: Export Terraform Output for Function App Name
      #   id: export-tf-output
      #   run: |
      #     cd terraform
      #     # Capture the Terraform output for function_app_name
      #     function_app_name=$(terraform output -raw function_app_name)
      #     # Use the multiline syntax to safely export the output
      #     echo "function_app_name<<EOF" >> $GITHUB_OUTPUT
      #     echo "$function_app_name" >> $GITHUB_OUTPUT
      #     echo "EOF" >> $GITHUB_OUTPUT

    outputs:
      function_app_name: ${{ steps.export-tf-output.outputs.function_app_name }}

  deploy-function:
    name: "Deploy Azure Function App"
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install azure-functions-core-tools@4 --ignore-installed

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.terraform.outputs.function_app_name }}
          package: "."
          respect-funcignore: true
          scm-do-build-during-deployment: true
